### PR TITLE
Changes to flow/cloudbees-cd workshop

### PR DESCRIPTION
**Pull request by smavadia-cb**
Changes to flow/cloudbees-cd workshop

### CODE REVIEW

**Review by jpflug — APPROVED** [review]
Looks good

**Comment by smavadia-cb** [comment]
Thanks man.



*Regards*

~s


*--------------------Sunil Mavadia*

Director, Global Enterprise Technical Architecture

*Global Channels, Alliances, Partners & SIs*

P + Signal/Whatsapp: +1.720.340.9532 | Timezone:MST

E: ***@***.***
Twitter: @SunilMavadia

LinkedIn: https://www.linkedin.com/in/sunilmavadia/

**Comment by smavadia-cb** [comment]
There is something going on with the ci workshop that doesn't apply to this workshop. Thus I am not seeing the changes in the repo, even after you approve the changes.  Can you take a look at the error and either fix it, or let me know what I need to change?
Thanks
Sunil

**Comment by kmadel** [comment]
@smavadia-cb The slides for the labs need to go under the top level labs folder and that is where you would create a `cloudbees-cd` directory, and then the slides would go into a `content` directory. You also need a `config.toml` file in the `cloudbees-cd` - all of the slides use the `based` directory for the Hugo theme, archetypes, etc. Take a look at https://github.com/cloudbees-days/cloudbees-field-workshops/tree/pipeline-workshop/labs/cloudbees-ci-pipeline as an example. At that point we can setup a job that will build a preview of the CD lab content.

**Comment by zvercodebender** [comment]
Not merged

**Pull request closed without merging**
